//
//	image sequence viewer
//	
//	cobranail@gmail.com
//	2008/12/13
//

// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef isv_h
#define isv_h
#include <FL/Fl.H>
#include <stdio.h>
#include <string.h>
#include <FL/Fl_Image.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Button *imgview;
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *indicator;
#include <FL/Fl_Button.H>
extern Fl_Button *setting;
extern Fl_Button *pausebutton;
extern Fl_Button *playbackbutton;
extern Fl_Button *filebutton;
#include <FL/Fl_Box.H>
extern Fl_Box *frameinfo;
#endif
